---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: emergency-example
    name: emergency-example
    namespace: default
spec:
    ports:
        - name: "http"
          protocol: TCP
          port: 8084
          targetPort: 8084
    selector:
        App: backend
status:
    loadBalancer: {}